@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam wrapWidth 300
LAYOUT_WITH_LEGEND()

Boundary(InnerCircleBoundary, "Inner Circle"){
        Boundary(AuthBoundary, "Auth") {
            Container(AuthUI, "Auth UI", "React/JS", "Pages for registration, authentication and password reset.")
            Container(AuthAPI, "Auth API", ".net 8", "API for authentication and token generation with user permissions.")
            ContainerDb(AuthDB, "Auth DB", "PostgreSQL", "Stores authentication information: login, password hash, etc.")
        }

        Boundary(AccountsBoundary, "Accounts") {
            Container(AccountsUI, "Accounts UI", "React/JS", "Pages for managing accounts, roles and tenants.")
            Container(AccountsAPI, "Accounts API", ".net 8", "API for managing accounts, roles and tenants.")
            ContainerDb(AccountsDB, "Accounts DB", "PostgreSQL", "Stores accounts, roles with permissions, tenants information.")
        }

        Boundary(EmployeesBoundary, "Employees") {
            Container(UI, "UI", "React/JS", "Pages for managing profile and list of employees.")
            Container(EmployeesAPI, "Employees API", ".net 8", "API for managing profile and list of employees.")
            ContainerDb(EmployeesDB, "Employees DB", "PostgreSQL", "Stores employee's information: name, corporate and personal email, etc.")
        }

        Boundary(DocumentsBoundary, "Documents") {
            Container(DocumentsUI, "Documents UI", "React/JS", "Pages for documents uploading and validation.")
            Container(DocumentsAPI, "Documents API", ".net 8", "API for documents validation.")
            ContainerDb(DocumentsDB, "Documents DB", "PostgreSQL", "Empty database.")
        }

        Boundary(CompensationsBoundary, "Compensations") {
            Container(CompensationsUI, "Compensations UI", "React/JS", "Pages for managing and requesting compensations.")
            Container(CompensationsAPI, "Compensations API", ".net 8", "API for managing and requesting compensations.")
            ContainerDb(CompensationsDB, "Compensations DB", "PostgreSQL", "Stores compensations information.")
        }

        Boundary(BooksBoundary, "Books") {
            Container(BooksUI, "Books UI", "React/JS", "Pages for borrowing and managing corporate library books.")
            Container(BooksAPI, "Books API", ".net 8", "API for borrowing and managing corporate library books.")
            ContainerDb(BooksDB, "Books DB", "PostgreSQL", "Stores corporate library books information.")
        }

        Boundary(TimeBoundary, "Time") {
            Container(TimeUI, "Time UI", "React/JS", "Pages for tracking and monitoring working time.")
            Container(TimeAPI, "Time API", ".net 8", "API for for tracking and monitoring working time.")
            ContainerDb(TimeDB, "Time DB", "PostgreSQL", "Stores working time entries.")
        }

        Container(EmailSender, "Email Sender", ".net 8", "Sends emails to employees on corporate email.")
        
        Container(ItemsAPI, "Items API", ".net 9", "API for inventory management")
        
        Container(MentoringAPI, "Mentoring API", ".net 9", "API to track the progress of mentoring, one-on-ones, and staff-reviews, etc.")
    }

    Container_Ext(MailBox, "Mail.ru mailbox", "External Service", "")

    Rel(AuthUI, AuthAPI, "Makes API calls to", "REST")
    Rel_U(AuthAPI, AccountsAPI, "Get permissions for user with correct creds", "REST")
    Rel(AuthAPI, AuthDB, "Read from and write to")
    Rel(AuthAPI, EmailSender, "Sends password-related emails")

    Rel(AccountsUI, AccountsAPI, "Makes API calls to", "REST")
    Rel(AccountsAPI, AccountsDB, "Read from and write to")
    Rel(AccountsAPI, EmployeesAPI, "Request for creation and deletion of an employee")
    Rel(AccountsAPI, AuthAPI, "Create/delete user after account creation/deletion", "REST")

    Rel(EmployeesAPI, EmployeesDB, "Read from and write to", "REST")

    Rel(UI, EmployeesAPI, "Makes API calls to", "REST")


    Rel(DocumentsUI, DocumentsAPI, "Makes API calls to")
    Rel(DocumentsAPI, EmailSender, "Sends document-related emails")
    Rel(DocumentsAPI, EmployeesAPI, "Requests employee data")


    Rel(CompensationsUI, CompensationsAPI, "Makes API calls to", "REST")
    Rel(CompensationsAPI, CompensationsDB, "Read from and write to")
    Rel(CompensationsAPI, EmployeesAPI, "Requests employee data")

    Rel(BooksUI, BooksAPI, "Makes API calls to", "REST")
    Rel(BooksAPI, BooksDB, "Read from and write to")
    Rel(BooksAPI, EmployeesAPI, "Requests employee data")

    Rel(TimeUI, TimeAPI, "Makes API calls to", "REST")
    Rel(TimeAPI, TimeDB, "Read from and write to")

    Rel(EmailSender, MailBox, "Sends emails", "SMTP")

    Rel(ItemsAPI, EmployeesAPI, "Requests employees data")

    Rel(MentoringAPI, EmployeesAPI, "Requests employees data")
@enduml